# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('training_class', models.CharField(max_length=10)),
                ('graduation_year', models.IntegerField(default=0)),
            ],
        ),
    ]
