# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleasure_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educator',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='educator',
            name='last_name',
            field=models.CharField(default='lastname', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educator',
            name='trained_communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educator',
            name='trained_culture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educator',
            name='trained_identity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educator',
            name='trained_love',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educator',
            name='trained_values',
            field=models.BooleanField(default=False),
        ),
    ]
