# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pleasure_app', '0005_auto_20170221_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='trained_communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_training', to='pleasure_app.Training'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='trained_culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cul_training', to='pleasure_app.Training'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='trained_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_training', to='pleasure_app.Training'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='trained_love',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lov_training', to='pleasure_app.Training'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='trained_values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='val_training', to='pleasure_app.Training'),
        ),
    ]
