# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleasure_app', '0006_auto_20170221_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('educators', models.ManyToManyField(to='pleasure_app.Educator')),
            ],
        ),
    ]
