# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pleasure_app', '0007_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='educators',
        ),
        migrations.AddField(
            model_name='presentation',
            name='educator1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator1', to='pleasure_app.Educator'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='educator2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator2', to='pleasure_app.Educator'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='location',
            field=models.CharField(default='default_loc', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter', to='pleasure_app.Educator'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='subject',
            field=models.CharField(choices=[('COM', 'Communication'), ('VAL', 'Values'), ('ID', 'Identity'), ('LOV', 'Love'), ('CUL', 'Culture')], max_length=3),
        ),
    ]
