# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleasure_app', '0009_educator_athena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='educator',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(to='pleasure_app.Educator'),
        ),
    ]
