# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleasure_app', '0015_auto_20170316_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
